#!/command/with-contenv bash

source /assets/functions/00-container
prepare_service single
PROCESS_NAME="postgres"
output_off


cat <<EOF

*****************************************************************************************
*                                                                                       *
*                    END OF LIFE NOTICE OCTOBER 06, 2025                                *
*                               tiredofit/postgres                                      *
*                                                                                       *
* This image is no longer maintained as of and will not receive updates.                *
*                                                                                       *
* A successor image is available at:                                                    *
*                                                                                       *
* Repository | Documentation:                                                           *
*   - https://github.com/nfrastack/container-postgres                                   *
*                                                                                       *
* Image Registries:                                                                     *
*   - https://hub.docker.com/r/nfrastack/postgres                                       *
*   - https://github.com/nfrastack/container-postgres/pkgs/container/container-postgres *
*                                                                                       *
* Please visit https://nfrastack.com for more information.                              *
*                                                                                       *
*****************************************************************************************

EOF

bootstrap_filesystem
initialize_cluster
configure_server
control_server start
create_databases
configure_replication
configure_monitoring
control_server stop
print_info "PostgreSQL init process complete - ready for start up."
liftoff
